spring:
  datasource:                             # Database password
    driver-class-name: org.postgresql.Driver           # PostgreSQL driver class name
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # Hibernate dialect for PostgreSQL
    hibernate:
      ddl-auto: update                                     # Hibernate DDL auto (update, create, none, validate)
  profiles:
    active:
    - prod

server:
  port: 9292                                               # Port number for the Spring Boot application

